### ISSUE TITLE
Can js and css be integrated?

### ISSUE THREAD

**Issue by 107295472** [exceptionless/Exceptionless.UI#223] opened 2022-05-17 03:14 UTC
cdn.jsdelivr.net Can't access, my network can't be China Mobile

**Comment by niemyjski** [comment] 2022-05-17 11:17
Hello,

This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/195. We'd be more than happy to accept a pr for bringing in the dependencies but at this time we can't keep changing the cdn every year when a global acceptable cdn gets banned.

**Closed by niemyjski** 2022-05-17 11:17 UTC
