### ISSUE TITLE
Add disable registration setting to UI

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.UI#43] opened 2015-06-12 09:56 UTC
Instead of having to do this through a config file, maybe this can be added to Admin -> System (makes some sense here)?

**Comment by niemyjski** [comment] 2015-06-12 12:42
Here is the thing, the ui site is all static so this would need to be read from the server and configured there as well (new api, maybe on the admin controller). I think the better option would be to allow invites to go out and people to register if they have a valid invite token. Thoughts?

**Comment by Phyxion** [comment] 2015-06-12 12:44
An invite system would absolutely be an improvement over the current one and makes sense in this situation.

**Comment by niemyjski** [comment] 2016-01-12 18:56
I'm going to close this as by design. If you'd like to submit a pull request for a setting for this, I'd be more than happy to accept it.

**Closed by niemyjski** 2016-01-12 18:56 UTC
Labels: enhancement
