### ISSUE TITLE
Add local fallbacks for dependencies

### ISSUE THREAD

**Issue by laughinggoose** [exceptionless/Exceptionless.UI#50] opened 2015-09-16 21:03 UTC
If you have access to a self-hosted Exceptionless server but not to the internet at large, it is unusable due to the dependencies not being able to load.

**Comment by niemyjski** [comment] 2015-09-17 01:55
Would you mind submitting a pull request for this. I think we should use the pattern that prefers cdn and falls back to local files. The only issue I see is currently we are only including the minified scripts in the root folder. We'd almost have to include a scripts folder with the vendor dependencies.

**Comment by niemyjski** [comment] 2015-10-11 21:11
@laughinggoose would you be able to make a pull request for this?

**Comment by laughinggoose** [comment] 2015-10-12 19:46
I can look into it, but I'm not an expert at this.

**Comment by niemyjski** [comment] 2015-10-13 23:16
Ok, I'll try to put together some pseudo code for this.

**Comment by niemyjski** [comment] 2016-01-12 18:35
I'm going to close this as by design, if you'd like to submit a pull request that uses the cdn and falls back to the self hosted scripts. I'd be more than happy to merge it in.

**Closed by niemyjski** 2016-01-12 18:35 UTC
Labels: enhancement, feature request
