### ISSUE TITLE
No sign up button when registrations are disabled

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.UI#24] opened 2015-04-14 17:29 UTC
The sign up button should be removed when registrations are disabled. Maybe also redirect the #/signup page to login in that case (with a toast message).

**Comment by niemyjski** [comment] 2015-04-14 17:35
Currently disabling of signups in a server side feature so we'd need to add this to the client side app as well. Would you mind submitting a pull request for this?

**Comment by niemyjski** [comment] 2016-01-12 19:07
I'm closing this issue as this is by design. If you'd like to submit a pull request that uses configuration to disable this button I'd be more than happy to include it.

**Closed by niemyjski** 2016-01-12 19:07 UTC
Labels: feature request, help wanted
