### ISSUE TITLE
Indicate which project an event belongs to

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless.UI#41] opened 2015-06-09 21:02 UTC
I would like to be able to see which project an event belongs to, in the different overviews, eg. Dashboard, Most Resent, Most Frequent.
Maby with a colored label or just a colored icon with a mouse over help text with the project name.
Or some other way to quickly see what exceptions are from the same project.

**Comment by niemyjski** [comment] 2016-01-12 18:55
Duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/10

**Closed by niemyjski** 2016-01-12 18:55 UTC
Labels: enhancement, feature request
