### ISSUE TITLE
Leave expanded menu status

### ISSUE THREAD

**Issue by matteomigliore** [exceptionless/Exceptionless.UI#4] opened 2015-03-04 15:49 UTC
It should be useful that the menu remains expanded even if I go to an event detail.

**Comment by niemyjski** [comment] 2015-03-04 16:12
What menu are you referring to?

**Comment by matteomigliore** [comment] 2015-03-04 16:29
The application menu (Exceptions, Log messages...), if you go to the detail of an event, it collpses.

**Comment by niemyjski** [comment] 2015-03-04 16:32
This only happens on the mobile layout. What is your browser size? Is your sidebar pinned?

**Comment by matteomigliore** [comment] 2015-03-04 16:34
In my case it happens also in desktop mode, browser Maxthon.

**Comment by niemyjski** [comment] 2015-03-04 16:41
I just downloaded Maxthon and couldn't reproduce but I did come across some ui layout bugs with buttons (not sure what rendering engine they are using but we have no issues in chrome, firefox or ie).

 Can you please record a screencast of this issue using [jing project](http://www.techsmith.com/jing.html). Also please have your developer console open so we can see if there is any javascript errors.

**Comment by matteomigliore** [comment] 2015-03-04 16:49
Sure :) http://screencast.com/t/n9Zx3mdBG.

**Comment by niemyjski** [comment] 2015-03-04 17:02
Thanks for the video, I thought that the whole sidebar was collapsing. This is a known behavior that we will address when the new angular router is released. The reason it collapses like that is you are navigating to a new route and that sidebar is dynamically created based on the current route. This also effects other things like clicking on a project link on the event overview won't remember your previous route (type:error etc..)

**Comment by niemyjski** [comment] 2016-01-12 18:52
I'm closing this as by design, we don't have the previous route state to keep it open. We're still waiting on angular 1.5 to be released so we can do something about this. We are working towards making it simpler and easier to navigate around the site

**Closed by niemyjski** 2016-01-12 18:52 UTC
Labels: enhancement
